# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b29e0e60-21b1-4fb1-9b92-603041abbf2e";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/b29e0e60-21b1-4fb1-9b92-603041abbf2e";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/var/lib/libvirt/images" =
    { device = "/dev/disk/by-uuid/b29e0e60-21b1-4fb1-9b92-603041abbf2e";
      fsType = "btrfs";
      options = [ "subvol=@vms" "compress=zstd" "noatime" "nofail" ];
    };

  fileSystems."/home/emilio/ai_storage" =
    { device = "/dev/disk/by-uuid/b29e0e60-21b1-4fb1-9b92-603041abbf2e";
      fsType = "btrfs";
      options = [ "subvol=@ai" "compress=zstd:3" "noatime" "nofail" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2BA5-BD2A";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
