-- Auto-generated by matugen
-- Do not edit manually (unless you enjoy pain)

return {
  -- Base16 core
  base00 = "{{ colors.background }}",
  base01 = "{{ colors.surface }}",
  base02 = "{{ colors.surface_variant }}",
  base03 = "{{ colors.outline }}",
  base04 = "{{ colors.on_surface_variant }}",
  base05 = "{{ colors.on_background }}",
  base06 = "{{ colors.on_background }}",
  base07 = "{{ colors.on_background }}",

  -- Accents
  base08 = "{{ colors.error }}",          -- red
  base09 = "{{ colors.tertiary }}",       -- orange
  base0A = "{{ colors.secondary }}",      -- yellow
  base0B = "{{ colors.primary }}",        -- green
  base0C = "{{ colors.secondary }}",      -- cyan
  base0D = "{{ colors.primary }}",        -- blue
  base0E = "{{ colors.tertiary }}",       -- purple
  base0F = "{{ colors.error }}",
}

