-- Auto-generated by matugen
-- DO NOT EDIT MANUALLY

local M = {}

M.type = "dark"

M.base_30 = {
  white = "{{ colors.on_background }}",
  darker_black = "{{ colors.surface }}",
  black = "{{ colors.background }}",
  black2 = "{{ colors.surface_variant }}",
  one_bg = "{{ colors.surface_variant }}",
  one_bg2 = "{{ colors.surface_variant }}",
  one_bg3 = "{{ colors.outline }}",

  grey = "{{ colors.outline }}",
  grey_fg = "{{ colors.on_surface_variant }}",
  grey_fg2 = "{{ colors.on_surface_variant }}",
  light_grey = "{{ colors.on_surface }}",

  red = "{{ colors.error }}",
  orange = "{{ colors.tertiary }}",
  yellow = "{{ colors.secondary }}",
  green = "{{ colors.primary }}",
  cyan = "{{ colors.secondary }}",
  blue = "{{ colors.primary }}",
  purple = "{{ colors.tertiary }}",
  pink = "{{ colors.tertiary }}",

  line = "{{ colors.outline }}",
  statusline_bg = "{{ colors.surface }}",
  lightbg = "{{ colors.surface_variant }}",
  pmenu_bg = "{{ colors.primary }}",
  folder_bg = "{{ colors.primary }}",
}

M.base_16 = {
  base00 = "{{ colors.background }}",
  base01 = "{{ colors.surface }}",
  base02 = "{{ colors.surface_variant }}",
  base03 = "{{ colors.outline }}",
  base04 = "{{ colors.on_surface_variant }}",
  base05 = "{{ colors.on_background }}",
  base06 = "{{ colors.on_background }}",
  base07 = "{{ colors.on_background }}",

  base08 = "{{ colors.error }}",
  base09 = "{{ colors.tertiary }}",
  base0A = "{{ colors.secondary }}",
  base0B = "{{ colors.primary }}",
  base0C = "{{ colors.secondary }}",
  base0D = "{{ colors.primary }}",
  base0E = "{{ colors.tertiary }}",
  base0F = "{{ colors.error }}",
}

M.polish_hl = {
  ["@tag"] = { fg = "{{ colors.tertiary }}" },
  ["@tag.delimiter"] = { fg = "{{ colors.primary }}" },
}

local ok, base46 = pcall(require, "base46")
if ok then
  M = base46.override_theme(M, "onedark")
end

return M

